//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elearn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int id { get; set; }
        public Nullable<int> idstu { get; set; }
        public string comment1 { get; set; }
        public Nullable<int> idpost { get; set; }
    
        public virtual post post { get; set; }
        public virtual Ueaser Ueaser { get; set; }
    }
}
