//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elearn.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ElearnEntities : DbContext
    {
        public ElearnEntities()
            : base("name=ElearnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<exame> exames { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<markexame> markexames { get; set; }
        public virtual DbSet<mistak> mistaks { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<post> posts { get; set; }
        public virtual DbSet<qu> qus { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Ueaser> Ueasers { get; set; }
        public virtual DbSet<UserInGroup> UserInGroups { get; set; }
    }
}
