//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elearn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int id { get; set; }
        public Nullable<int> iduser { get; set; }
        public Nullable<int> state { get; set; }
        public string username { get; set; }
        public Nullable<int> role { get; set; }
        public string token { get; set; }
    
        public virtual Ueaser Ueaser { get; set; }
    }
}
