//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elearn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class markexame
    {
        public int id { get; set; }
        public Nullable<int> idexame { get; set; }
        public Nullable<int> mark { get; set; }
        public Nullable<int> idstu { get; set; }
        public Nullable<int> fullmark { get; set; }
    
        public virtual exame exame { get; set; }
        public virtual Ueaser Ueaser { get; set; }
    }
}
