//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elearn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mistak
    {
        public int id { get; set; }
        public Nullable<int> idqu { get; set; }
        public Nullable<int> idstu { get; set; }
        public Nullable<int> idexam { get; set; }
        public Nullable<int> Nummistak { get; set; }
        public Nullable<int> CorectAn { get; set; }
    
        public virtual exame exame { get; set; }
        public virtual qu qu { get; set; }
        public virtual Ueaser Ueaser { get; set; }
    }
}
