//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elearn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public qu()
        {
            this.mistaks = new HashSet<mistak>();
            this.Notes = new HashSet<Note>();
            this.posts = new HashSet<post>();
        }
    
        public string Qu1 { get; set; }
        public string An1 { get; set; }
        public string An2 { get; set; }
        public string An3 { get; set; }
        public string An4 { get; set; }
        public Nullable<int> QreAn { get; set; }
        public int id { get; set; }
        public string reason_an { get; set; }
        public Nullable<int> id_emp { get; set; }
        public Nullable<int> idexame { get; set; }
    
        public virtual exame exame { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mistak> mistaks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Notes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<post> posts { get; set; }
    }
}
